apiVersion: v1
kind: Secret
metadata:
  name: fcg-secrets
  namespace: fcg
type: Opaque
stringData:
  # --- Banco de dados ---
  SQL_SA_PASSWORD: "CHANGE_ME"
  USERS_CONNECTION_STRING: "Server=sqlserver;Database=FCGUsers;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True"
  CATALOG_CONNECTION_STRING: "Server=sqlserver;Database=FCGCatalog;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True"
  PAYMENTS_CONNECTION_STRING: "Server=sqlserver;Database=FCGPayments;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True"

  # --- JWT ---
  JWT_KEY: "CHANGE_ME"

  # --- Admin inicial ---
  ADMIN_PASSWORD: "CHANGE_ME"

  # --- Chave interna entre APIs ---
  INTERNAL_API_KEY: "CHANGE_ME"

  # --- Datadog ---
  DD_API_KEY: "CHANGE_ME"

  # --- Redis ---
  REDIS_CONNECTION: "redis:6379"
