apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: fcg
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
